[telegram]
bot_token = '1234567890:ABCDEF1234567890ABCDEF1234567890ABC'
admin_id = 1

[etherscan]
api_key = '1234567890ABCDEF1234567890ABCDEF'

[database]
dns = 'sqlite+aiosqlite:///database.db'

[logging]
level = 20
format = '[%(levelname)s] %(asctime)s - %(name)s - %(message)s'
